using UnityEngine;

namespace Fougerite.Events
{
    /// <summary>
    /// This runs when a supply signal was dropped on the ground.
    /// </summary>
    public class SupplySignalExplosionEvent
    {
        private readonly SignalGrenade _grenade;
        private bool _cancel = false;
        private Vector3 _pos;

        public SupplySignalExplosionEvent(SignalGrenade gr, Vector3 pos)
        {
            _grenade = gr;
            _pos = pos;
        }

        public bool Cancelled
        {
            get { return _cancel; }
        }

        /// <summary>
        /// Returns the Grenade's instance
        /// </summary>
        public SignalGrenade SignalGrenade
        {
            get { return _grenade; }
        }

        /// <summary>
        /// This is the random position of the airdrop generated by rust.
        /// Don't be surprised, It's actually in the air, and It's not the grenade's position.
        /// </summary>
        public Vector3 AirdropPosition
        {
            get { return _pos; }
        }

        /// <summary>
        /// Cancels the event.
        /// </summary>
        public void Cancel()
        {
            _cancel = true;
        }
    }
}